import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { ASSISTANTS, METADATA_VERSION, QA_AI_RULES_PACKAGE, type Assistant } from './constants.js';
import { getCliPackageProvenance, type CliPackageProvenance } from './setup-log.js';
import type { GeneratedFile } from './generators/types.js';

export const SETUP_METADATA_PATH = '.assistant-setup/ca-ai-tools-setup.json';
export const SETUP_STATUS_PATH = '.assistant-setup/SETUP_STATUS.md';

export type FileOwnership = 'managed' | 'protected' | 'structured';
export type FileBaseline = 'generated' | 'adopted' | 'merged';

export type SetupFileRecord = {
  ownership: FileOwnership;
  contentHash: string;
  sourceHash: string;
  sourceVersion: string;
  baseline: FileBaseline;
};

export type McpTargets = {
  cursorFile: boolean;
  projectRootFile: boolean;
};

export type SetupMetadata = {
  version: typeof METADATA_VERSION;
  assistants: Assistant[];
  playwrightMcp: McpTargets;
  figmaMcp: McpTargets;
  devEnvironment: {
    file: '.dev-environment.md';
    generated: true;
  };
  pageWorkflowContext: {
    file: '.assistant-setup/page-workflow-context.md';
    generated: true;
  };
  linearCliReference: {
    file: 'LINEAR_CLI.md';
    generated: true;
  };
  qaAiRules: {
    enabled: boolean;
    package: typeof QA_AI_RULES_PACKAGE;
  };
  provenance: CliPackageProvenance;
  files: Record<string, SetupFileRecord>;
};

export type LoadedSetupMetadata =
  | { kind: 'missing' }
  | { kind: 'invalid'; detail: string }
  | { kind: 'legacy'; raw: Record<string, unknown> }
  | { kind: 'current'; metadata: SetupMetadata };

export type MetadataConfiguration = {
  assistants: Assistant[];
  playwrightMcp: McpTargets;
  figmaMcp: McpTargets;
  qaAiRulesEnabled: boolean;
};

export function createSetupStatusContent(
  configuration: MetadataConfiguration,
  provenance = getCliPackageProvenance(),
): string {
  const marker = {
    id: 'ca-ai-tools-setup',
    schemaVersion: METADATA_VERSION,
    package: provenance.package,
    packageVersion: provenance.version,
    templateRevision: provenance.templateRevision,
    assistants: configuration.assistants,
  };

  return `<!-- ca-ai-tools-setup-status ${JSON.stringify(marker)} -->
# AI Assistant Setup Status

This tracked file confirms that \`${provenance.package}\` generated the repository's AI assistant setup.
Its presence does not guarantee that the installed templates are the latest available release.

## Agent check

- If this file is missing, report that the repository setup is absent or incomplete.
- Read the marker above to identify the installed package and template revision.
- Run this read-only check once before setup-sensitive work:

\`\`\`bash
npx -p ${provenance.package}@stable ca-ai-tools-setup check .
\`\`\`

- Exit code \`0\`: the tracked setup matches the selected package release.
- Exit code \`2\`: the setup is stale, incomplete, or needs migration; report it and propose an update PR.
- Exit code \`1\`: the check failed; report the error instead of treating the setup as current.
- Never run \`update\` or \`--force\` without explicit developer approval.

Do not edit this file manually; a setup or update run refreshes it deterministically.
`;
}

const STRUCTURED_PATHS = new Set(['.cursor/mcp.json', '.mcp.json', '.claude/settings.json', 'AGENTS.md']);

const PROTECTED_PATHS = new Set([
  '.cursorrules',
  '.cursorignore',
  'CLAUDE.md',
  '.dev-environment.md',
  '.assistant-setup/page-workflow-context.md',
]);

function isAssistant(value: unknown): value is Assistant {
  return typeof value === 'string' && (ASSISTANTS as readonly string[]).includes(value);
}

function isMcpTargets(value: unknown): value is McpTargets {
  if (!value || typeof value !== 'object') {
    return false;
  }

  const targets = value as Record<string, unknown>;

  return typeof targets.cursorFile === 'boolean' && typeof targets.projectRootFile === 'boolean';
}

function isFileOwnership(value: unknown): value is FileOwnership {
  return value === 'managed' || value === 'protected' || value === 'structured';
}

function isFileBaseline(value: unknown): value is FileBaseline {
  return value === 'generated' || value === 'adopted' || value === 'merged';
}

function parseFileRecords(value: unknown): Record<string, SetupFileRecord> | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return null;
  }

  const records: Record<string, SetupFileRecord> = {};

  for (const [filePath, rawRecord] of Object.entries(value as Record<string, unknown>)) {
    const normalizedPath = normalizeSetupPath(filePath);

    if (!isSafeSetupPath(normalizedPath) || records[normalizedPath] !== undefined) {
      return null;
    }

    if (!rawRecord || typeof rawRecord !== 'object' || Array.isArray(rawRecord)) {
      return null;
    }

    const record = rawRecord as Record<string, unknown>;

    if (
      !isFileOwnership(record.ownership) ||
      typeof record.contentHash !== 'string' ||
      typeof record.sourceHash !== 'string' ||
      typeof record.sourceVersion !== 'string' ||
      !isFileBaseline(record.baseline)
    ) {
      return null;
    }

    records[normalizedPath] = {
      ownership: ownershipForPath(normalizedPath),
      contentHash: record.contentHash,
      sourceHash: record.sourceHash,
      sourceVersion: record.sourceVersion,
      baseline: record.baseline,
    };
  }

  return sortFileRecords(records);
}

function parseCurrentMetadata(raw: Record<string, unknown>): SetupMetadata | null {
  if (raw.version !== METADATA_VERSION || !Array.isArray(raw.assistants)) {
    return null;
  }

  const assistants = raw.assistants.filter(isAssistant);
  const provenance = raw.provenance;
  const qaAiRules = raw.qaAiRules;
  const fileRecords = parseFileRecords(raw.files);

  if (
    assistants.length === 0 ||
    !isMcpTargets(raw.playwrightMcp) ||
    !isMcpTargets(raw.figmaMcp) ||
    !provenance ||
    typeof provenance !== 'object' ||
    typeof (provenance as Record<string, unknown>).package !== 'string' ||
    typeof (provenance as Record<string, unknown>).version !== 'string' ||
    typeof (provenance as Record<string, unknown>).releaseCommit !== 'string' ||
    typeof (provenance as Record<string, unknown>).templateRevision !== 'string' ||
    !qaAiRules ||
    typeof qaAiRules !== 'object' ||
    typeof (qaAiRules as Record<string, unknown>).enabled !== 'boolean' ||
    fileRecords === null
  ) {
    return null;
  }

  return {
    version: METADATA_VERSION,
    assistants,
    playwrightMcp: raw.playwrightMcp,
    figmaMcp: raw.figmaMcp,
    devEnvironment: {
      file: '.dev-environment.md',
      generated: true,
    },
    pageWorkflowContext: {
      file: '.assistant-setup/page-workflow-context.md',
      generated: true,
    },
    linearCliReference: {
      file: 'LINEAR_CLI.md',
      generated: true,
    },
    qaAiRules: {
      enabled: (qaAiRules as Record<string, unknown>).enabled as boolean,
      package: QA_AI_RULES_PACKAGE,
    },
    provenance: {
      package: (provenance as Record<string, unknown>).package as string,
      version: (provenance as Record<string, unknown>).version as string,
      releaseCommit: (provenance as Record<string, unknown>).releaseCommit as string,
      templateRevision: (provenance as Record<string, unknown>).templateRevision as string,
    },
    files: fileRecords,
  };
}

export function normalizeSetupPath(filePath: string): string {
  return filePath.replaceAll('\\', '/');
}

export function isSafeSetupPath(filePath: string): boolean {
  const normalized = normalizeSetupPath(filePath);
  const segments = normalized.split('/');

  return (
    normalized.length > 0 &&
    !normalized.includes('\0') &&
    !path.posix.isAbsolute(normalized) &&
    !path.win32.isAbsolute(normalized) &&
    segments.every((segment) => segment.length > 0 && segment !== '.' && segment !== '..') &&
    path.posix.normalize(normalized) === normalized
  );
}

export function hashContent(content: string): string {
  const normalizedContent = content.replace(/\r\n?/gu, '\n');

  return `sha256:${createHash('sha256').update(normalizedContent, 'utf8').digest('hex')}`;
}

export function ownershipForPath(filePath: string): FileOwnership {
  const normalized = normalizeSetupPath(filePath);

  if (STRUCTURED_PATHS.has(normalized)) {
    return 'structured';
  }

  if (PROTECTED_PATHS.has(normalized)) {
    return 'protected';
  }

  return 'managed';
}

export function sortFileRecords(records: Record<string, SetupFileRecord>): Record<string, SetupFileRecord> {
  return Object.fromEntries(Object.entries(records).sort(([left], [right]) => left.localeCompare(right)));
}

export function createSetupMetadata(
  configuration: MetadataConfiguration,
  files: GeneratedFile[],
  installedContent: ReadonlyMap<string, string> = new Map(),
  provenance = getCliPackageProvenance(),
): SetupMetadata {
  const records: Record<string, SetupFileRecord> = {};

  for (const file of files) {
    const normalizedPath = normalizeSetupPath(file.path);

    if (normalizedPath === SETUP_METADATA_PATH) {
      continue;
    }

    if (!isSafeSetupPath(normalizedPath)) {
      throw new Error(`Generated setup path is unsafe: ${file.path}`);
    }

    const actualContent = installedContent.get(normalizedPath) ?? file.content;
    const sourceHash = hashContent(file.content);
    const contentHash = hashContent(actualContent);

    records[normalizedPath] = {
      ownership: ownershipForPath(normalizedPath),
      contentHash,
      sourceHash,
      sourceVersion: provenance.version,
      baseline: contentHash === sourceHash ? 'generated' : 'adopted',
    };
  }

  return {
    version: METADATA_VERSION,
    assistants: configuration.assistants,
    playwrightMcp: configuration.playwrightMcp,
    figmaMcp: configuration.figmaMcp,
    devEnvironment: {
      file: '.dev-environment.md',
      generated: true,
    },
    pageWorkflowContext: {
      file: '.assistant-setup/page-workflow-context.md',
      generated: true,
    },
    linearCliReference: {
      file: 'LINEAR_CLI.md',
      generated: true,
    },
    qaAiRules: {
      enabled: configuration.qaAiRulesEnabled,
      package: QA_AI_RULES_PACKAGE,
    },
    provenance,
    files: sortFileRecords(records),
  };
}

export function serializeSetupMetadata(metadata: SetupMetadata): string {
  return `${JSON.stringify({ ...metadata, files: sortFileRecords(metadata.files) }, null, 2)}\n`;
}

export function loadSetupMetadata(targetDir: string): LoadedSetupMetadata {
  const metadataPath = path.join(targetDir, SETUP_METADATA_PATH);

  if (!fs.existsSync(metadataPath)) {
    return { kind: 'missing' };
  }

  let raw: unknown;

  try {
    raw = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
  } catch (error) {
    return {
      kind: 'invalid',
      detail: error instanceof Error ? error.message : 'Metadata is not valid JSON.',
    };
  }

  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    return { kind: 'invalid', detail: 'Metadata root must be a JSON object.' };
  }

  const record = raw as Record<string, unknown>;

  if (record.version === 5 || record.version === undefined) {
    return { kind: 'legacy', raw: record };
  }

  const metadata = parseCurrentMetadata(record);

  if (!metadata) {
    return {
      kind: 'invalid',
      detail: `Unsupported or malformed metadata schema ${String(record.version ?? 'unknown')}.`,
    };
  }

  return { kind: 'current', metadata };
}
